# Board-level layer for LuckFox RK3506 boards (Core3506).
# Contains machine configs, board-specific DTS, and wks partition layouts.
# Pairs with meta-rockchip-rk3506 (the SoC vendor layer).

BBPATH .= ":${LAYERDIR}"

BBFILES += "\
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "luckfox-bsp"
BBFILE_PATTERN_luckfox-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_luckfox-bsp = "9"

LAYERDEPENDS_luckfox-bsp = "core"
LAYERSERIES_COMPAT_luckfox-bsp = "scarthgap styhead"
