default luckfox-a
label luckfox-a
    kernel /zImage
    fdt /rk3506b-luckfox-core3506.dtb
    append root=PARTLABEL=rootfs_a rootfstype=ext4 rootwait earlycon=uart8250,mmio32,0xff0a0000,115200n8 console=ttyFIQ0,115200 panic=10
